### ISSUE TITLE
xcode error

### ISSUE THREAD

**Issue by ghost** [julian-park/speedyswim#1]
Hi, I have a problem 
![zrzut ekranu 2016-01-09 o 13 19 39](https://cloud.githubusercontent.com/assets/6787484/12215990/a7ca52ba-b6d3-11e5-923f-bd29662cda84.png)

**Comment by julian-park** [comment]
It seems like the code is written in Swift 1 and your Xcode uses Swift 2. Try running the app again using Swift 1!

**Comment by ghost** [comment]
But how, i have Xcode 7.2

**Comment by ghost** [comment]
?

**Comment by julian-park** [comment]
Try using the Swift Migrator tool. More info here: http://stackoverflow.com/questions/30766297/can-swift-1-code-run-on-ios-9
